// Frases kawaii, dicas, curiosidades e incentivos para o mascote
const mascotPhrases = [
  'Meow! Explore animes incríveis! ✨',
  'Dica: Use palavras-chave para achar animes raros!',
  'Sabia que gatos amam cultura otaku? 🐾',
  'Clique em mim para uma nova dica kawaii!',
  'Nyaa~ Já tomou água hoje? 💧',
  'Otaku também precisa descansar! 😸',
  'Busque por "Ghibli" e veja a magia! 🌸',
  'Você já sorriu hoje? 😺',
  'Anime do dia: tente algo novo!',
  'Compartilhe fofura com seus amigos!',
  'Gatos ronronam para mostrar carinho. E você?',
  'Dica: Favorite seus gatinhos preferidos!',
  'Streaks diários desbloqueiam conquistas! 🔥',
  'Que tal um gif kawaii para animar seu dia?',
  'Anime + gato = perfeição!',
  'Já tentou buscar por "One Piece"?',
  'Dica: Clique em "Favoritar" para guardar seu gatinho!',
  'Você é incrível! Continue explorando!',
  'Dica: Use o autocomplete para achar animes mais rápido!',
  'Fofura nunca é demais! 🐱',
  'Anime favorito? Compartilhe com a gente!',
  'Dica: Experimente todos os recursos do Yume.gg!',
  'Gatos trazem sorte para otakus! 🍀',
  'Já viu os animes em alta hoje?',
  'Dica: Volte amanhã para mais conquistas!',
  'Nyaa~ Que tal um wallpaper novo?',
  'Você já bateu seu recorde de streak?',
  'Dica: O mascote sempre tem uma nova frase pra você!',
  'Anime é melhor com amigos!',
  'Fique de olho nas novidades do Yume.gg!',
  'Dica: Use temas diferentes para mudar o visual!',
  'Gatinhos e animes: a combinação perfeita!',
  'Você já recomendou Yume.gg para alguém hoje?',
  'Dica: Experimente o quiz de personalidade!',
  'Continue explorando, sempre tem algo novo!',
  'Nyaa~ Você merece um dia incrível!',
  'Dica: Veja seus favoritos na CuteCorner!',
  'Otaku feliz, mascote feliz! 😸',
  'Dica: Use o botão de compartilhar para espalhar fofura!',
  'Gatos também amam música! Já ouviu a playlist?',
  'Dica: Experimente o gerador de ícones kawaii!',
  'Fofura compartilhada é fofura dobrada!',
  'Dica: Veja as conquistas que você já desbloqueou!',
  'Nyaa~ Volte sempre para mais diversão!',
];

export default mascotPhrases;
